baseurl = "https://osl.amanohina.com"
copyright = "&copy; 2020 OSL Japan"
theme = "Nai"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  organization = "OSL Official Site (@OSL)"
  organization_url = "https://OSL.AMANOHINA.COM"
  avatar = "//setss.png"
  email = "osl@amanohina.com"
  telegram = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = "KashimaNai"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  highlight = true
  highlight_languages = ["swift","objectivec"]
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ["main.css"]
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Book',  # 1
    'Book chapter'  # 2
  ]

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:osl@amanohina.com"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/Armoeb"

  [[params.social]]
    icon = "weibo"
    icon_pack = "fa"
    link = "//weibo.com/remusic"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/OSLP"

  [[menu.main]]
    name = "Home"
    url = "#about"
    weight = 1

   [[menu.main]]
    name = "Talks"
    url = "#talks"
    weight = 4

  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 6

[languages.en]
  languageCode = "en-us"
  title = "OSL Japan"
  name = "OSL"
  role = "Cyber Security Solution"
  address = "JR Shinjuku Miraina Tower 23F, 4-1-6 Shinjuku, Shinjuku-ku, Tokyo, 160-0022, Japan"
  office_hours = "Please send an email for appointment"
